# Sub-Exercise 7: Handling Void Methods with Exceptions

## Scenario:
You want to simulate failure when a `void` method throws an exception (e.g., deleting a record that doesnâ€™t exist).

## Objectives:
- Use `doThrow(...).when(mock).voidMethod(...)`
- Test how your system handles exceptions from void methods
