# Sub-Exercise 4: Exception Testing

## Scenario:
You want to ensure your code throws the correct exceptions when bad input is passed.

## Objectives:
- Use `assertThrows()` to test exceptions
- Confirm that exceptions are handled correctly
